#!/bin/bash

VERSION=${1}
DOCKERHUB_PASSWORD=${2}
DOCKERHUB_USERNAME=${3}

APP_NAME_NISTAGRAM_FRONT=nistagram-front

APP_IMAGE_NAME_NISTAGRAM_FRONT=${DOCKERHUB_USERNAME}/${APP_NAME_NISTAGRAM_FRONT}:${VERSION}

APP_ARTIFACT_NAME_NISTAGRAM_FRONT=${APP_NAME_NISTAGRAM_FRONT}:${VERSION}.tar

DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_NISTAGRAM_FRONT}" \
--no-cache \
.

docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_PASSWORD}
docker push "$APP_IMAGE_NAME_NISTAGRAM_FRONT"